### PR TITLE
#282 Use first line of commit message for PR title when only one commit

### PR DESCRIPTION
**Pull request by docent-net**
Looks like only new_request_pull() should be changed

### CODE REVIEW

**Comment by pypingou** [comment]
Pull-requests should be made on pagure, why making it here?

**Comment by docent-net** [comment]
@pypingou it's just a habit. When I asked you about this some time ago I remembered that github was legit; but no problem - I'll stick to Pagure :)

```
19:47 < docent> pingou: one question about pagure development; I see that repo is hosted on github and also on fedora's pagure. Not sure - which one should I use as upstream?
21:14 < pingou> docent: it's nice to use pagure, helps testing it :)
21:14 < pingou> docent: but technically both are kept in sync
```

**Comment by pypingou** [comment]
I thought you meant about getting the code, otherwise I try to keep the development/contribution part in pagure itself :)

**Comment by pypingou** [comment]
Could you re-open the pull-request on https://pagure.io/pagure ? You don't even need to fork the repo there you can open a remote pull-request from your fork on github :)

Thanks

**Pull request closed without merging**
