### PR TITLE
issue #1084 : Redirect .git extension in URL to repos page

### PR DESCRIPTION
**Pull request by abhishekg785**

### CODE REVIEW

**Comment by vivekanand1101** [comment]
@abhishekg785 open the PR at pagure.io itself

**Comment by pypingou** [comment]
This is also clearly not the way we want it, you should create a new route ending with .git and in that route redirect to the normal one

**Comment by pypingou** [comment]
An example where this code would fail: project: foo.bar :)

**Comment by abhishekg785** [comment]
@pypingou  
But foo.bar is an invalid name for a project

**Pull request closed without merging**
